#!/bin/bash
# Regenerate configs/codex/config.managed.toml from the live ~/.codex/config.toml.
#
# Codex cannot be symlinked at its config: it writes project trust entries and
# hook trust hashes into config.toml continuously (131 and 18 of them on this
# machine at time of writing), so the file is part config, part runtime state.
# The repo therefore carries only the config half, and apply-config.sh merges it
# back over whatever runtime state the target machine already has.
#
# Run this after changing Codex settings by hand or through its UI, so the repo
# does not drift from the machine. `git diff` afterwards shows what changed.
#
# Usage:
#   ./scripts/codex/capture-config.sh            regenerate the template
#   ./scripts/codex/capture-config.sh --dry-run  print to stdout instead

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
SOURCE="$CODEX_HOME/config.toml"
TEMPLATE="$REPO_ROOT/configs/codex/config.managed.toml"
DRY_RUN=false

[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

if [[ ! -f "$SOURCE" ]]; then
    printf '%s\n' "codex: no config at $SOURCE" >&2
    exit 1
fi

# Sections dropped from the template:
#   [projects]         per-machine directory trust (137 entries here) — absolute
#                      paths that mean nothing on another host, and Codex does
#                      not expand $HOME in TOML values so they cannot be made
#                      portable. apply-config.sh preserves the target machine's
#                      own block, and ~/.local/bin/codex-workspace-trust-sync
#                      regenerates it from scratch on a new machine.
#   [hooks.state.*]    sha256 trust hashes tied to this config file's path.
#   [tui.*]            NUX counters and other transient UI state.
#   [[skills.config]]  addresses skills by version-pinned plugin-cache path.
# Dropped keys:
#   notify             an absolute path to a per-machine notify hook.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    cat <<'HEADER'
# Managed Codex configuration — generated by scripts/codex/capture-config.sh.
#
# Do not hand-edit: change ~/.codex/config.toml, then re-run the capture script.
# Applied by scripts/codex/apply-config.sh, which layers this over the target
# machine's own project trust, hook trust hashes, plugins and MCP servers.
HEADER
    awk '
        function is_header(line) { return line ~ /^\[/ }
        function drop_header(line) {
            return line ~ /^\[projects(\.|\])/ ||
                   line ~ /^\[hooks\.state(\.|\])/ ||
                   line ~ /^\[tui\./
        }
        is_header($0) { skip = drop_header($0) }
        skip { next }
        /^notify[[:space:]]*=/ { next }
        # [[skills.config]] entries address a skill by absolute path into the
        # plugin cache, and that path carries the plugin version
        # (.../github/0.1.8-2841cf9749ae/...). It breaks on the next plugin
        # update, not just on another machine, so it is runtime state.
        /^\[\[skills\.config\]\]/ { drop_block = 1; next }
        drop_block && /^\[/ { drop_block = 0 }
        drop_block { next }
        { print }
    ' "$SOURCE"
} > "$tmp"

if [[ "$DRY_RUN" == "true" ]]; then
    cat "$tmp"
    exit 0
fi

mkdir -p "$(dirname "$TEMPLATE")"
cp "$tmp" "$TEMPLATE"
printf '%s\n' "codex: captured $SOURCE -> $TEMPLATE ($(wc -l < "$TEMPLATE") lines)"
