#!/usr/bin/env bash
# Rebuild Codex's exact-path project trust table from the local workspace.

set -euo pipefail
umask 077

codex_home="${CODEX_HOME:-$HOME/.codex}"
config_file="$codex_home/config.toml"
workspace_root="${CODEX_WORKSPACE_ROOT:-$HOME/workspace-agent}"
current_path="${1:-}"

if [[ ! -f "$config_file" ]]; then
  printf 'Codex config not found: %s\n' "$config_file" >&2
  exit 1
fi

if [[ ! -d "$workspace_root" ]]; then
  printf 'Workspace root not found: %s\n' "$workspace_root" >&2
  exit 1
fi
if LC_ALL=C printf '%s' "$workspace_root" | grep -q '[[:cntrl:]]'; then
  printf 'Workspace root contains unsupported control characters: %q\n' "$workspace_root" >&2
  exit 1
fi

# Multiple terminals can launch Codex at once. Serialize sync processes where
# flock is available; macOS has no system flock, so the atomic final move is
# still the last line of defence there.
if command -v flock >/dev/null 2>&1; then
  exec 9>"$codex_home/.trust-sync.lock"
  flock 9
fi

path_file=$(mktemp "$codex_home/.trust-paths.XXXXXX")
table_file=$(mktemp "$codex_home/.trust-table.XXXXXX")
output_file=$(mktemp "$codex_home/.config.XXXXXX")
trap 'rm -f -- "$path_file" "$table_file" "$output_file"' EXIT

# Preserve existing, real directories outside the disposable workspace.
{
  sed -n -E 's/^"([^"]+)"[[:space:]]*=.*trust_level.*/\1/p' "$config_file"
  sed -n -E 's/^\[projects\."([^"]+)"\][[:space:]]*$/\1/p' "$config_file"
} | while IFS= read -r project_path; do
  if [[ -d "$project_path" && \
        "$project_path" != "$workspace_root" && \
        "$project_path" != "$workspace_root/"* ]] && \
        ! LC_ALL=C printf '%s' "$project_path" | grep -q '[[:cntrl:]]'; then
    printf '%s\n' "$project_path"
  fi
done > "$path_file"

# Codex project trust is exact-path based. Include the workspace itself, every
# current first-level directory, and every nested Git repository/worktree root.
{
  printf '%s\n' "$workspace_root"
  find "$workspace_root" -mindepth 1 -maxdepth 1 -type d -print \
    | while IFS= read -r project_path; do
        if [[ -d "$project_path" ]] && \
           ! LC_ALL=C printf '%s' "$project_path" | grep -q '[[:cntrl:]]'; then
          printf '%s\n' "$project_path"
        fi
      done
  find "$workspace_root" -mindepth 1 -maxdepth 3 -name .git -print -prune \
    | while IFS= read -r git_marker; do
        project_path=$(dirname "$git_marker")
        if [[ -d "$project_path" ]] && \
           ! LC_ALL=C printf '%s' "$project_path" | grep -q '[[:cntrl:]]'; then
          printf '%s\n' "$project_path"
        fi
      done
} >> "$path_file"

# When launched from a deeper checkout, add both the exact working directory
# and its Git root without recursively walking dependency trees.
if [[ -n "$current_path" && -d "$current_path" && \
      ("$current_path" == "$workspace_root" || "$current_path" == "$workspace_root/"*) ]] && \
      ! LC_ALL=C printf '%s' "$current_path" | grep -q '[[:cntrl:]]'; then
  printf '%s\n' "$current_path" >> "$path_file"
  git_root=$(git -C "$current_path" rev-parse --show-toplevel 2>/dev/null || true)
  if [[ -n "$git_root" ]]; then
    printf '%s\n' "$git_root" >> "$path_file"
  fi
fi
LC_ALL=C sort -u -o "$path_file" "$path_file"

{
  printf '[projects]\n'
  printf '# Generated by ~/.local/bin/codex-workspace-trust-sync.\n'
  printf '# Codex trust is exact-path based; rerun after cloning or removing worktrees.\n'
  while IFS= read -r project_path; do
    escaped_path=${project_path//\\/\\\\}
    escaped_path=${escaped_path//\"/\\\"}
    printf '"%s" = { trust_level = "trusted" }\n' "$escaped_path"
  done < "$path_file"
} > "$table_file"

awk -v replacement="$table_file" '
  function emit_replacement(line) {
    while ((getline line < replacement) > 0) print line
    close(replacement)
    emitted = 1
  }

  function is_project_header(line) {
    return line ~ /^\[projects(\.|\])/
  }

  skipping_projects {
    if ($0 ~ /^\[/) {
      skipping_projects = 0
    } else {
      next
    }
  }

  is_project_header($0) {
    if (!emitted) emit_replacement()
    skipping_projects = 1
    next
  }

  { print }

  END {
    if (!emitted) {
      print ""
      emit_replacement()
    }
  }
' "$config_file" > "$output_file"

if command -v python3 >/dev/null 2>&1 && python3 -c 'import tomllib' >/dev/null 2>&1; then
  if ! python3 - "$output_file" <<'PY'
import pathlib
import sys
import tomllib

tomllib.loads(pathlib.Path(sys.argv[1]).read_text())
PY
  then
    printf 'Generated Codex trust config is invalid; existing config was left untouched.\n' >&2
    exit 1
  fi
fi

chmod 600 "$output_file"
if ! cmp -s "$config_file" "$output_file"; then
  mv -f -- "$output_file" "$config_file"
fi
