#!/bin/bash
# Capture the ~/.claude/skills symlink farm into configs/claude/skills.manifest.
#
# Claude Code only auto-discovers ~/.claude/skills/<name>/SKILL.md, one level
# deep, so the skills here are grouped into category directories and reached
# through the skill-index skill instead. Every one of them is a symlink into a
# source repo, which makes the farm pure derived state — this manifest records
# the mapping so install.sh can lay it back down without needing `agt`.
#
# Format, one skill per line:
#   <category>/<name><TAB><repo><TAB><path-within-repo>
#
# Usage:
#   ./scripts/claude/capture-skills.sh            write the manifest
#   ./scripts/claude/capture-skills.sh --dry-run  print it instead

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS_DIR="$HOME/.claude/skills"
MANIFEST="$REPO_ROOT/configs/claude/skills.manifest"
DRY_RUN=false

[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# Repos the farm may point into, longest prefix first so nested paths resolve
# to the right one. Keys are the tokens written into the manifest.
declare -A SKILL_REPOS=(
    [agents]="$HOME/workspace/agents"
    [agent-skills]="$HOME/personal/agent-skills"
)

if [[ ! -d "$SKILLS_DIR" ]]; then
    printf '%s\n' "claude: no skills dir at $SKILLS_DIR" >&2
    exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    printf '%s\n' "# Generated by scripts/claude/capture-skills.sh — do not hand-edit."
    printf '%s\n' "# <category>/<name><TAB><repo><TAB><path-within-repo>"

    for category_dir in "$SKILLS_DIR"/*/; do
        category=$(basename "$category_dir")
        # Flat skills (skill-index, muxa-report) are managed on their own.
        [[ -f "$category_dir/SKILL.md" ]] && continue

        for skill_dir in "$category_dir"*/; do
            skill=$(basename "$skill_dir")
            [[ -f "$skill_dir/SKILL.md" ]] || continue

            # Only symlinks are reproducible; a real directory here is a local
            # copy that belongs in a repo before it can be restored.
            if [[ ! -L "${skill_dir%/}" ]]; then
                printf '%s\n' "claude: warning: $category/$skill is a real directory, not reproducible" >&2
                continue
            fi

            target=$(readlink -f "${skill_dir%/}")
            matched=false
            for repo in "${!SKILL_REPOS[@]}"; do
                root=$(readlink -f "${SKILL_REPOS[$repo]}" 2>/dev/null) || continue
                if [[ "$target" == "$root/"* ]]; then
                    printf '%s\t%s\t%s\n' "$category/$skill" "$repo" "${target#"$root"/}"
                    matched=true
                    break
                fi
            done
            $matched || printf '%s\n' "claude: warning: $category/$skill points outside known repos ($target)" >&2
        done
    done
} > "$tmp"

if [[ "$DRY_RUN" == "true" ]]; then
    cat "$tmp"
    exit 0
fi

mkdir -p "$(dirname "$MANIFEST")"
cp "$tmp" "$MANIFEST"
printf '%s\n' "claude: captured $(grep -cv '^#' "$MANIFEST") skills -> $MANIFEST"
