#!/usr/bin/env bash
# Build the sandbox that docs/demo.tape records in, and print the exports the
# recording shell needs.
#
#   eval "$(docs/demo-setup.sh)"   # build it, enter it
#   docs/demo-teardown.sh          # remove all of it
#
# The installer in the recording is the real one — the real progress box, the
# real spinner, the real symlinks, the real summary. What is faked is
# everything *outside* it: Homebrew, git, curl, rustup, cargo, chsh. Three
# reasons, and each one on its own would be enough:
#
#   * a README GIF must not install software on the machine that renders it;
#   * it must not touch the operator's $HOME, which a dotfiles installer
#     exists to rewrite;
#   * a real `--core` run takes minutes, and nobody watches a two-minute GIF.
#
# So HOME points at a scratch directory and PATH leads with a directory of
# shims that sleep for a believable moment and exit 0. Everything the viewer
# sees the *installer* do is real; everything it would have done to the
# machine is not.
#
# Informational output goes to stderr on purpose: stdout carries the exports.

set -euo pipefail

ROOT="${SETTINGS_DEMO_ROOT:-/tmp/settings-demo}"
SCALE="${SETTINGS_DEMO_SCALE:-1}"   # stretch or compress every shim's delay
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Start from clean. An interrupted render leaves a half-built sandbox behind,
# and a half-built sandbox is worse than none: the shims that did get written
# make the missing ones look like installer bugs.
SETTINGS_DEMO_ROOT="$ROOT" bash "$SCRIPT_DIR/demo-teardown.sh"

HOME_DIR="$ROOT/home"
BIN="$ROOT/bin"
mkdir -p "$HOME_DIR" "$BIN"

# Scale a delay. Kept in awk because bash has no float arithmetic and these
# are all fractions of a second.
d() { awk -v x="$1" -v s="$SCALE" 'BEGIN { printf "%.2f", x * s }'; }

# shim <name> <seconds>, dispatch body (optional) on stdin.
#
# The body runs before the sleep and may exit early — that is how `brew list`
# answers "not installed" while `brew install` answers "took a moment, worked".
shim() {
    local name=$1 delay
    delay="$(d "$2")"
    {
        printf '%s\n' \
            '#!/usr/bin/env bash' \
            '# Demo shim, generated by docs/demo-setup.sh. Installs nothing.'
        cat
        [[ "$delay" == "0.00" ]] || printf 'sleep %s\n' "$delay"
        printf 'exit 0\n'
    } > "$BIN/$name"
    chmod +x "$BIN/$name"
}

# ── Package managers ─────────────────────────────────────────────────────
# `pkg_installed` asks `brew list <pkg>`, and a shim that answered 0 there
# would make every package report "already installed" — a progress display
# with nothing to display. Inside the sandbox nothing is installed, so the
# query says so and the install path runs.
shim brew 1.0 <<'BODY'
case "${1:-}" in
    list|ls)         exit 1 ;;
    --prefix)        echo "/opt/homebrew"; exit 0 ;;
    --version)       echo "Homebrew 4.6.0"; exit 0 ;;
esac
BODY

shim apt-get 1.0 </dev/null
shim apt 1.0 </dev/null
shim dpkg 0 <<'BODY'
exit 1   # nothing installed in the sandbox
BODY
# sudo is shimmed rather than passed through: a recording that can escalate is
# a recording that can do the one thing this sandbox exists to prevent.
shim sudo 0.6 </dev/null

# ── Network and VCS ──────────────────────────────────────────────────────
# git_clone_pinned runs init → remote add → fetch → checkout, and only three
# of those four sit behind a spinner. `remote add` returns instantly so the
# pacing matches what the operator would see on a fast connection.
# Unquoted heredoc: the delays are substituted now, the shell variables are
# escaped so they survive to run time.
shim git 0 <<BODY
sub=""
while [ \$# -gt 0 ]; do
    case "\$1" in
        -C|-c) shift 2; continue ;;
        -*)    shift; continue ;;
        *)     sub="\$1"; break ;;
    esac
done
case "\$sub" in
    fetch|clone) sleep $(d 1.1) ;;
    checkout)    sleep $(d 0.5) ;;
    init)        sleep $(d 0.4) ;;
esac
BODY

shim curl 0.9 </dev/null
shim wget 0.9 </dev/null

# ── Toolchains ───────────────────────────────────────────────────────────
# rust.sh and tools.sh gate on `command_exists cargo-binstall` before they
# will install anything, so these have to exist as files, not just as answers.
shim rustup 1.2 </dev/null
shim cargo 1.1 </dev/null
shim cargo-binstall 1.1 </dev/null
shim rustc 0 <<'BODY'
echo "rustc 1.90.0 (demo)"
exit 0
BODY
shim uv 0 <<'BODY'
echo "uv 0.9.0 (demo)"
exit 0
BODY
shim npm 1.0 </dev/null
shim tar 0.6 </dev/null

# ── Things that would change the machine ─────────────────────────────────
# None of these is reached by the components the tape records. They are here
# because the next tape might record one that is, and a missed shim in that
# situation is not a broken GIF — it is a changed login shell.
shim chsh 0.5 </dev/null
shim defaults 0.2 </dev/null
shim osascript 0.2 </dev/null
shim killall 0.2 </dev/null
shim softwareupdate 1.0 </dev/null
shim mas 1.0 </dev/null
shim hidutil 0.2 </dev/null
shim launchctl 0.2 </dev/null

# The marker demo-teardown.sh looks for before it removes anything. Written
# last so it also means "this sandbox was built all the way through".
printf 'built by docs/demo-setup.sh at %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" > "$ROOT/.settings-demo"

echo "sandbox ready at $ROOT" >&2

# stdout: what the recording shell evals. PATH deliberately drops Homebrew and
# every other user bin directory — not to be tidy, but because a real `eza` or
# `nvim` on PATH turns the whole recording into a wall of "(already
# installed)".
cat <<EOF
export SETTINGS_DEMO_ROOT='$ROOT'
export HOME='$HOME_DIR'
export PATH='$BIN:/usr/bin:/bin:/usr/sbin:/sbin'
export XDG_CONFIG_HOME='$HOME_DIR/.config'
export XDG_DATA_HOME='$HOME_DIR/.local/share'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
cd '$REPO_DIR'
EOF
